### ISSUE TITLE
Standardised identifier for myst documents

### ISSUE THREAD

**Issue by chrisjsewell** [executablebooks/myst-spec#15]
It may be useful to have a standard way of signalling that a document is myst, and even perhaps the myst-spec version it is compliant with, particularly if using the (non-specific) `.md` file extension.

For example, in the top-matter

```yaml
---
format: myst
format-version: "0.1.0"
---
```
